package mimex;

import arc.Core;
import arc.files.Fi;
import arc.util.Log;

abstract class MetadataExtractor {
    protected final String newLine = System.lineSeparator();
    protected final StringBuilder sbr = new StringBuilder();

    protected MetadataExtractor() {
        sbr.append("// DO NOT EDIT! Generated by mimex - Mindustry Metadata Extractor").append(newLine);
    }

    public abstract void extract();

    protected void writeToFile(String file) {
        Fi fi = Core.files.local("mimex-" + file + ".txt");
        fi.writeString(sbr.toString());
        Log.info("Created local file " + fi.absolutePath());
        sbr.setLength(0);
    }
}
