package mimex;

import arc.Core;
import arc.files.Fi;
import arc.graphics.Color;
import arc.graphics.Colors;
import arc.struct.Seq;
import arc.util.Log;
import mindustry.Vars;
import mindustry.core.Version;
import mindustry.logic.GlobalConstants;
import mindustry.logic.LAccess;
import mindustry.logic.LAssembler;
import mindustry.logic.LExecutor;
import mindustry.mod.Mod;
import mindustry.world.Block;
import mindustry.world.blocks.distribution.ItemBridge;
import mindustry.world.blocks.distribution.MassDriver;
import mindustry.world.blocks.logic.LogicBlock;
import mindustry.world.blocks.power.PowerNode;
import mindustry.world.blocks.units.UnitFactory;
import mindustry.world.meta.BuildVisibility;

import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.HashSet;
import java.util.IdentityHashMap;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;
import java.util.TreeMap;

public class MindustryMetadataExtractor extends Mod {
    private static final int expectedVersion = 6;

    private final String newLine = System.lineSeparator();
    private final StringBuilder sbr = new StringBuilder();

    public MindustryMetadataExtractor() {
        Log.info("MindustryMetadataExtractor constructor.");
    }

    @Override
    public void init() {
        super.init();
        if (Version.number == expectedVersion) {
            writeIcons();
            writeColors();
            writeBlocks();
            writeItems();
            writeLiquids();
            writeUnits();
            writeLAccess();
            writeVars();
        }
    }

    private void writeToFile(String file) {
        Fi fi = Core.files.local("mimex-" + file + ".txt");
        fi.writeString(sbr.toString());
        Log.info("Created local file " + fi.absolutePath());
        sbr.setLength(0);
    }

    private void writeIcons() {
        sbr.append("// DO NOT EDIT! Generated by mimex - Mindustry Metadata Extractor").append(newLine);

        try (Scanner scan = new Scanner(Core.files.internal("icons/icons.properties").read(512))) {
            while (scan.hasNextLine()) {
                String line = scan.nextLine();
                String[] s = line.split("[|=]");
                if (s.length < 3) continue;
                String name = s[2].toUpperCase().replaceAll("-UI$", "");
                sbr.append(name).append(';').append(s[1]).append(';').append(s[0]).append(newLine);
            }
        }

        writeToFile("icons");
    }

    private void writeColors() {
        sbr.append("// DO NOT EDIT! Generated by mimex - Mindustry Metadata Extractor").append(newLine);

        sbr.append("name").append(';')
                .append("rgba")
                .append(newLine);

        Map<String, Color> map = new TreeMap<>();
        Colors.getColors().each(map::put);
        map.entrySet().stream()
                .filter(e -> !Character.isUpperCase(e.getKey().charAt(0)))
                .forEach(e -> sbr.append(e.getKey()).append(';').append(e.getValue()).append(newLine));

        writeToFile("colors");
    }

    private final Map<BuildVisibility, String> visibilityMap = new IdentityHashMap<>();

    {
        visibilityMap.put(BuildVisibility.hidden, "hidden");
        visibilityMap.put(BuildVisibility.shown, "shown");
        visibilityMap.put(BuildVisibility.debugOnly, "debugOnly");
        visibilityMap.put(BuildVisibility.editorOnly, "editorOnly");
        visibilityMap.put(BuildVisibility.sandboxOnly, "sandboxOnly");
        visibilityMap.put(BuildVisibility.campaignOnly, "campaignOnly");
        visibilityMap.put(BuildVisibility.lightingOnly, "lightingOnly");
        visibilityMap.put(BuildVisibility.ammoOnly, "ammoOnly");
    }

    private double getRange(Block block) {
        if (block instanceof PowerNode p) {
            return p.laserRange;
        } else if (block instanceof ItemBridge b) {
            return b.range;
        } else if (block instanceof MassDriver d) {
            return d.range / Vars.tilesize;
        } else if (block instanceof LogicBlock l) {
            return l.range / Vars.tilesize;
        } else {
            return 0;
        }
    }

    private void appendUnitPlans(UnitFactory unitFactory) {
        for (int i = 0; i < unitFactory.plans.size; i++) {
            if (i > 0) sbr.append('|');
            sbr.append(unitFactory.plans.get(i).unit.name);
        }
    }

    private void writeBlocks() {
        sbr.append("// DO NOT EDIT! Generated by mimex - Mindustry Metadata Extractor").append(newLine);

        sbr.append("name")
                .append(';').append("id")
                .append(';').append("logicId")
                .append(';').append("visibility")
                .append(';').append("size")
                .append(';').append("subclass")
                .append(';').append("configurable")
                .append(';').append("category")
                .append(';').append("range")
                .append(';').append("hasItems")
                .append(';').append("acceptsItems")
                .append(';').append("separateItemCapacity")
                .append(';').append("itemCapacity")
                .append(';').append("noSideBlend")
                .append(';').append("unloadable")
                .append(';').append("hasLiquids")
                .append(';').append("outputsLiquid")
                .append(';').append("liquidCapacity")
                .append(';').append("hasPower")
                .append(';').append("consumesPower")
                .append(';').append("outputsPower")
                .append(';').append("connectedPower")
                .append(';').append("conductivePower")
                .append(';').append("maxNodes")
                .append(';').append("outputFacing")
                .append(';').append("rotate")
                .append(';').append("unitPlans")
                .append(newLine);

        Vars.content.blocks().each(block -> {
            sbr.append(block.name)
                    .append(';').append(block.id)
                    .append(';').append(-1)
                    .append(';').append(visibilityMap.get(block.buildVisibility))
                    .append(';').append(block.size)
                    .append(';').append(block.subclass.getSimpleName())
                    .append(';').append(block.configurable)
                    .append(';').append(block.category)
                    .append(';').append(getRange(block))
                    .append(';').append(block.hasItems)
                    .append(';').append(block.acceptsItems)
                    .append(';').append("")
                    .append(';').append(block.itemCapacity)
                    .append(';').append("")
                    .append(';').append(block.unloadable)
                    .append(';').append(block.hasLiquids)
                    .append(';').append(block.outputsLiquid)
                    .append(';').append(block.liquidCapacity)
                    .append(';').append(block.hasPower)
                    .append(';').append(block.consumesPower)
                    .append(';').append(block.outputsPower)
                    .append(';').append("")
                    .append(';').append("")
                    .append(';').append(block instanceof PowerNode p ? p.maxNodes : 0)
                    .append(';').append(block.outputFacing)
                    .append(';').append(block.rotate)
                    .append(';');
            if (block instanceof UnitFactory f) {
                appendUnitPlans(f);
            }
            sbr.append(newLine);
        });

        writeToFile("blocks");
    }

    private void writeItems() {
        sbr.append("// DO NOT EDIT! Generated by mimex - Mindustry Metadata Extractor").append(newLine);

        sbr.append("name")
                .append(';').append("id")
                .append(';').append("logicId")
                .append(newLine);

        Vars.content.items().each(item -> sbr.append(item.name)
                .append(';').append(item.id)
                .append(';').append(-1)
                .append(newLine));

        writeToFile("items");
    }

    private void writeLiquids() {
        sbr.append("// DO NOT EDIT! Generated by mimex - Mindustry Metadata Extractor").append(newLine);

        sbr.append("name")
                .append(';').append("id")
                .append(';').append("logicId")
                .append(newLine);

        Vars.content.liquids().each(liquid -> sbr.append(liquid.name)
                .append(';').append(liquid.id)
                .append(';').append(-1)
                .append(newLine));

        writeToFile("liquids");
    }

    private void writeUnits() {
        sbr.append("// DO NOT EDIT! Generated by mimex - Mindustry Metadata Extractor").append(newLine);

        sbr.append("name")
                .append(';').append("id")
                .append(';').append("logicId")
                .append(newLine);

        Vars.content.units().each(unit -> sbr.append(unit.name)
                .append(';').append(unit.id)
                .append(';').append(-1)
                .append(newLine));

        writeToFile("units");
    }


    private void writeLAccess() {
        sbr.append("// DO NOT EDIT! Generated by mimex - Mindustry Metadata Extractor").append(newLine);

        sbr.append("name")
                .append(';').append("ordinal")
                .append(';').append("isObj")
                .append(';').append("senseable")
                .append(';').append("controls")
                .append(';').append("settable")
                .append(';').append("parameters")
                .append(newLine);


        Set<LAccess> senseable = new HashSet<>(Arrays.asList(LAccess.senseable));
        Set<LAccess> controls = new HashSet<>(Arrays.asList(LAccess.controls));

        for (LAccess l : LAccess.all) {
            sbr.append(l.name())
                    .append(';').append(l.ordinal())
                    .append(';').append(l.isObj)
                    .append(';').append(senseable.contains(l))
                    .append(';').append(controls.contains(l))
                    .append(';').append("")
                    .append(';').append(String.join(",", l.params))
                    .append(newLine);
        }

        writeToFile("laccess");
    }

    private void writeVars() {
        try {
            sbr.append("// DO NOT EDIT! Generated by mimex - Mindustry Metadata Extractor").append(newLine);
            sbr.append("name")
                    .append(';').append("global")
                    .append(';').append("isobj")
                    .append(';').append("constant")
                    .append(';').append("numval")
                    .append(newLine);

            LAssembler lAssembler = LAssembler.assemble("noop");

            Field vars = GlobalConstants.class.getDeclaredField("vars");
            vars.setAccessible(true);
            Seq<LExecutor.Var> globalVars = (Seq<LExecutor.Var>) vars.get(Vars.constants);

            globalVars.forEach( e -> sbr.append(e.name)
                    .append(';').append("global")
                    .append(';').append(e.isobj)
                    .append(';').append(e.constant)
                    .append(';').append(e.numval)
                    .append(newLine));

            lAssembler.vars.forEach(e -> sbr.append(e.key)
                    .append(';').append("local")
                    .append(';').append(false)
                    .append(';').append(e.value.constant)
                    .append(';').append(0.0)
                    .append(newLine));

            writeToFile("vars");
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }
}
